# Form implementation generated from reading ui file '/home/erhoof/Developer/db_looker_u_t6_course_work/res/m_add_products.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_m_add_products_view(object):
    def setupUi(self, m_add_products_view):
        m_add_products_view.setObjectName("m_add_products_view")
        m_add_products_view.resize(618, 450)

        self.retranslateUi(m_add_products_view)
        QtCore.QMetaObject.connectSlotsByName(m_add_products_view)

    def retranslateUi(self, m_add_products_view):
        _translate = QtCore.QCoreApplication.translate
        m_add_products_view.setWindowTitle(_translate("m_add_products_view", "Dialog"))
