# Form implementation generated from reading ui file '/home/erhoof/Developer/db_looker_u_t6_course_work/res/new_manufacturer.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewManufacturer(object):
    def setupUi(self, NewManufacturer):
        NewManufacturer.setObjectName("NewManufacturer")
        NewManufacturer.resize(384, 276)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewManufacturer.sizePolicy().hasHeightForWidth())
        NewManufacturer.setSizePolicy(sizePolicy)
        self.label_2 = QtWidgets.QLabel(NewManufacturer)
        self.label_2.setGeometry(QtCore.QRect(9, 9, 220, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(NewManufacturer)
        self.buttonBox.setGeometry(QtCore.QRect(9, 243, 166, 24))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(NewManufacturer)
        self.widget.setGeometry(QtCore.QRect(9, 40, 361, 191))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_name)
        self.lineEdit_CEO = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_CEO.setObjectName("lineEdit_CEO")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_CEO)
        self.lineEdit_accountant = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_accountant.setObjectName("lineEdit_accountant")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_accountant)
        self.lineEdit_address = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_address)
        self.lineEdit_requisites = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_requisites.setObjectName("lineEdit_requisites")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_requisites)

        self.retranslateUi(NewManufacturer)
        QtCore.QMetaObject.connectSlotsByName(NewManufacturer)

    def retranslateUi(self, NewManufacturer):
        _translate = QtCore.QCoreApplication.translate
        NewManufacturer.setWindowTitle(_translate("NewManufacturer", "Новый Производитель"))
        self.label_2.setText(_translate("NewManufacturer", "Новый Производитель"))
        self.label.setText(_translate("NewManufacturer", "Название"))
        self.label_3.setText(_translate("NewManufacturer", "ФИО Директора"))
        self.label_4.setText(_translate("NewManufacturer", "ФИО Бухгалтера"))
        self.label_5.setText(_translate("NewManufacturer", "Физ. Адрес"))
        self.label_6.setText(_translate("NewManufacturer", "Реквизиты"))
