# Form implementation generated from reading ui file '/home/erhoof/Developer/db_looker_u_t6_course_work/views/gen/ui_new_order_view.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


